name: Site name

on: 
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get list of changed files
      id: changed-files
      run: |
        echo "Changed files:"
        git diff --name-only HEAD^ HEAD
        echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')"
        echo "files=$changed_files" >> $GITHUB_ENV

    - name: FTP-Deploy-Action
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        source: 'dist/*'
        target: '/website'
        port: 22
        strip_components: 1